name: back_massage_bot
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pytorch
  - matplotlib
  - setuptools>=65.0
  - pip
  - open3d>=0.18.0
  - pip:
    - opencv-python>=4.8.0  # opencv is better installed via pip due to binary compatibility
